// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/blog/blog.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	blog "github.com/kazukimurahashi12/webapp/domain/blog"
	user "github.com/kazukimurahashi12/webapp/domain/user"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// DeleteBlog mocks base method.
func (m *MockUseCase) DeleteBlog(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlog", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlog indicates an expected call of DeleteBlog.
func (mr *MockUseCaseMockRecorder) DeleteBlog(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlog", reflect.TypeOf((*MockUseCase)(nil).DeleteBlog), id)
}

// GetBlogByID mocks base method.
func (m *MockUseCase) GetBlogByID(id string) (*blog.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlogByID", id)
	ret0, _ := ret[0].(*blog.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlogByID indicates an expected call of GetBlogByID.
func (mr *MockUseCaseMockRecorder) GetBlogByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlogByID", reflect.TypeOf((*MockUseCase)(nil).GetBlogByID), id)
}

// GetBlogsByUserID mocks base method.
func (m *MockUseCase) GetBlogsByUserID(userID string) ([]blog.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlogsByUserID", userID)
	ret0, _ := ret[0].([]blog.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlogsByUserID indicates an expected call of GetBlogsByUserID.
func (mr *MockUseCaseMockRecorder) GetBlogsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlogsByUserID", reflect.TypeOf((*MockUseCase)(nil).GetBlogsByUserID), userID)
}

// GetUserByID mocks base method.
func (m *MockUseCase) GetUserByID(userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUseCaseMockRecorder) GetUserByID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUseCase)(nil).GetUserByID), userID)
}

// NewCreateBlog mocks base method.
func (m *MockUseCase) NewCreateBlog(b *blog.Blog) (*blog.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateBlog", b)
	ret0, _ := ret[0].(*blog.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCreateBlog indicates an expected call of NewCreateBlog.
func (mr *MockUseCaseMockRecorder) NewCreateBlog(blog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateBlog", reflect.TypeOf((*MockUseCase)(nil).NewCreateBlog), blog)
}

// NewCreateUser mocks base method.
func (m *MockUseCase) NewCreateUser(u *user.User) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCreateUser", u)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewCreateUser indicates an expected call of NewCreateUser.
func (mr *MockUseCaseMockRecorder) NewCreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCreateUser", reflect.TypeOf((*MockUseCase)(nil).NewCreateUser), user)
}

// UpdateBlog mocks base method.
func (m *MockUseCase) UpdateBlog(b *blog.Blog) (*blog.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlog", b)
	ret0, _ := ret[0].(*blog.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlog indicates an expected call of UpdateBlog.
func (mr *MockUseCaseMockRecorder) UpdateBlog(blog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlog", reflect.TypeOf((*MockUseCase)(nil).UpdateBlog), blog)
}
